Add support for region
sematext/ansible-install-sematext pull request #5
Opened 2024-11-19 15:51 UTC by cpipilas

Add support for 'region' in sematext-agent role.

2024-11-19 15:54 UTC, cpipilas commented
@boratanrikulu after merging, how this find it's way to https://galaxy.ansible.com/ui/standalone/roles/sematext/spm-monitor-install/install/?

2024-11-19 15:54 UTC, boratanrikulu requested changes
Can you also update the readme please? Also did you test it, is it working fine?

2024-11-20 12:52 UTC, cpipilas commented
> Can you also update the readme please? Also did you test it, is it working fine?

Tested and works well in EU using the following configuration:

```
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    region: EU
    infra_token: INFRA_TOKEN
  roles:
    - { role: sematext.spm-monitor-install }
 ```

2024-11-20 12:53 UTC, akshatagarwl approved these changes

2024-11-20 13:00 UTC, merged